version: '3.7'

services:
    web:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        environment:
            - SECRET_KEY=samplesecretkey123
            - ALLOWED_HOSTS=127.0.0.1,localhost
    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on:
            - web

volumes:
    static_data: