version: '3.2'

services:
  web:
    build: 
      context: ./django_blog
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - static_volume:/usr/src/django_blog/staticfiles
      - media_volume:/usr/src/django_blog/media_b
    ports:
      - 80:80
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=django_blog.settings
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/django_blog/staticfiles
      - media_volume:/usr/src/django_blog/media

    ports:
      - 1337:80
    depends_on:
      - web

volumes:
    static_volume:
    media_volume: