version: '3'

services:
  web:
    build: 
      context: .
    volumes:
      - ./django_blog:/django_blog
    ports:
      - 8000:8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
