version: '3.2'

services:
  web:
    build: 
      context: ./django_blog
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - static_volume:/usr/src/django_blog/staticfiles
      - media_volume:/usr/src/django_blog/media_b
    ports:
      - 90:80
    environment:
      - DJANGO_SETTINGS_MODULE=django_blog.settings
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/django_blog/staticfiles
      - media_volume:/usr/src/django_blog/media

    ports:
      - 80:80
    depends_on:
      - web

volumes:
    static_volume:
    media_volume: