# Generated by Django 3.0.7 on 2020-06-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Machine Learning'), ('RASPBERRY PI', 'Raspberry Pi,')], max_length=20, null=True),
        ),
    ]
