# Generated by Django 3.0.7 on 2020-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200624_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Machine Learning'), ('RASPBERRY PI', 'Raspberry Pi')], max_length=20, null=True),
        ),
    ]
