# Generated by Django 3.0.7 on 2020-07-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200624_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('read_stage', models.CharField(choices=[('READ', 'Read'), ('TO_READ', 'To Read'), ('READING', 'Reading')], max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MACHINE LEARNING', 'Machine Learning'), ('DJANGO', 'Django')], max_length=20, null=True),
        ),
    ]
